name: comment

on:
  issue_comment:
    types: [created]


env:
  SERVICE: acceptance-tests

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/deploy')
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: ./action
        with:
          spinnaker-topic: ${{ secrets.SPINNAKER_TOPIC }}
