name: comment

on:
  issue_comment:
    types: [created]

env:
  SERVICE: acceptance-tests

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/deploy')
    steps:
      - uses: actions/checkout@v3
      - run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo "pr_number=pr-$PR" >> $GITHUB_OUTPUT
      - uses: ./.github/actions
        with:
          comment-body: ${{ github.event.comment.body }}
          pr-number: ${{ github.event.pull_request.number }}