name: comment

on:
  issue_comment:
    types: [created]


env:
  SERVICE: acceptance-tests

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/deploy')
    steps:
      - uses: actions/checkout
      - uses: ./actions
        with:
          comment-body: ${{ github.event.comment.body }}
          gcp-project: ${{ secrets.GOOGLE_PROJECT_ID }}
          bot-token: ${{ secrets.BOT_TOKEN }}
          spinnaker-topic: ${{ secrets.SPINNAKER_TOPIC }}
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          helm-chart: ${{ env.SERVICE }}/${{ env.SERVICE }}-latest.tgz